[package]
name = "vynapse-core"
version = "0.1.0"
edition = "2024"

[dependencies]
vynapse-math = { path = "../vynapse-math" }
vynapse-common = { path = "../vynapse-common" }
rand = "0.9.1"
serde = "1.0.219"
thiserror = "2.0.12"
